services:
  php-web:
    build: docker
    ports:
      - "8080:80"
    volumes:
      - "./app:/var/www"
      - "./docker/php.ini:/usr/local/etc/php/php.ini"
    depends_on:
      - mariadb
  mariadb:
    image: mariadb:10.6.18
    restart: always
    ports:
      - "3307:3306"
    volumes:
      - "./docker/mariadb-data:/var/lib/mysql"
      - "./docker/taxi.sql:/docker-entrypoint-initdb.d/dump.sql"
    environment:
      - MARIADB_ROOT_PASSWORD=Azerty123
      - LANG=C.UTF-8
  myadmin:
    image: phpmyadmin/phpmyadmin
    ports:
      - "8000:80"
    environment:
      - PMA_ARBITRARY=0
      - PMA_HOST=mariadb
      - UPLOAD_LIMIT=50M
    restart: always
    depends_on:
      - mariadb
  composer:
    image: composer
    command:
      - install
    volumes:
      - "./app:/app"
    restart: "no"
  run-command:
    image: ubuntu:latest
    entrypoint: [ "/bin/bash", "-c" ]
    command: "\"cd /home/ubuntu && [ ! -f .env ] && echo '.env is missing. Copying .env.dev ...' && cp .env.dev .env\""
    volumes:
      - "./app:/home/ubuntu"
    restart: "no"