image: node:23
stages:
  - deploy
  - test

cache:
  key:
    files:
      - pnpm-lock.yaml
  paths:
    - node_modules/
    - .pnpm-store

before_script:
  - corepack enable
  - corepack prepare pnpm@latest-8 --activate
  - pnpm config set store-dir .pnpm-store
  - pnpm install

lint:
  stage: test
  script:
    - pnpm lint


plesk:
  stage: deploy
  only:
    - main
  script:
    # Clear destination directory on the Plesk server
    #- ssh $SSH_USERNAME@cloudplesk.ikdoeict.be "rm -rf $PLESK_DIRECTORY/*"

    # Install openssh-client if not available
    - 'command -v ssh-agent >/dev/null || ( apt-get update -y && apt-get install openssh-client -y )'
    - eval $(ssh-agent -s)
    - chmod 400 "$SSH_PRIVATE_KEY"
    - ssh-add "$SSH_PRIVATE_KEY"
    - mkdir -p ~/.ssh
    - chmod 700 ~/.ssh
    - pnpm build

    # Copy the dist folder to the Plesk server
    - scp -o StrictHostKeyChecking=no -r dist/. $SSH_USERNAME@cloudplesk.ikdoeict.be:$PLESK_DIRECTORY
